-- MySQL Script generated by MySQL Workbench
-- 09/30/16 15:59:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sword_vr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sword_vr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sword_vr` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sword_vr` ;

-- -----------------------------------------------------
-- Table `sword_vr`.`ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sword_vr`.`ADMINISTRADOR` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sword_vr`.`ESPECIALISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sword_vr`.`ESPECIALISTA` (
  `id_especialista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `ADMINISTRADOR_id_admin` INT NOT NULL,
  PRIMARY KEY (`id_especialista`),
  INDEX `fk_ESPECIALISTA_ADMINISTRADOR_idx` (`ADMINISTRADOR_id_admin` ASC),
  CONSTRAINT `fk_ESPECIALISTA_ADMINISTRADOR`
    FOREIGN KEY (`ADMINISTRADOR_id_admin`)
    REFERENCES `sword_vr`.`ADMINISTRADOR` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sword_vr`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sword_vr`.`PACIENTE` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dirección` VARCHAR(45) NOT NULL,
  `teléfono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sword_vr`.`CITAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sword_vr`.`CITAS` (
  `fecha_cita` DATE NOT NULL,
  `hora_inicio` VARCHAR(45) NOT NULL,
  `hora_fin` VARCHAR(45) NOT NULL,
  `ESPECIALISTA_id_especialista` INT NOT NULL,
  `PACIENTE_id_paciente` INT NULL,
  INDEX `fk_CITAS_ESPECIALISTA1_idx` (`ESPECIALISTA_id_especialista` ASC),
  INDEX `fk_CITAS_PACIENTE1_idx` (`PACIENTE_id_paciente` ASC),
  PRIMARY KEY (`PACIENTE_id_paciente`, `ESPECIALISTA_id_especialista`),
  CONSTRAINT `fk_CITAS_ESPECIALISTA1`
    FOREIGN KEY (`ESPECIALISTA_id_especialista`)
    REFERENCES `sword_vr`.`ESPECIALISTA` (`id_especialista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITAS_PACIENTE1`
    FOREIGN KEY (`PACIENTE_id_paciente`)
    REFERENCES `sword_vr`.`PACIENTE` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sword_vr`.`SESION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sword_vr`.`SESION` (
  `id_sesion` INT NOT NULL,
  `nombre_fobia` VARCHAR(45) NOT NULL,
  `diagnostico` VARCHAR(45) NOT NULL,
  `nivel_ambiente` CHAR(1) NOT NULL,
  `CITAS_id_cita` INT NOT NULL,
  `CITAS_ESPECIALISTA_id_especialista` INT NOT NULL,
  `CITAS_PACIENTE_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_sesion`),
  INDEX `fk_SESION_CITAS1_idx` (`CITAS_id_cita` ASC, `CITAS_ESPECIALISTA_id_especialista` ASC, `CITAS_PACIENTE_id_paciente` ASC),
  CONSTRAINT `fk_SESION_CITAS1`
    FOREIGN KEY (`CITAS_ESPECIALISTA_id_especialista` , `CITAS_PACIENTE_id_paciente`)
    REFERENCES `sword_vr`.`CITAS` (`ESPECIALISTA_id_especialista` , `PACIENTE_id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
